version: "3.9"

services:
  postgres_db:
    image: postgres:15
    container_name: postgres
    volumes:
        - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env

  questions-and-mp3conv:
    build:
      dockerfile: ./dockerfile
      context: .
    container_name: questions-and-mp3conv
    image: questions-and-mp3conv:latest
    depends_on:
      - postgres_db
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head | uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000

volumes:
  postgres_db:


