"""fix

Revision ID: 249185222e45
Revises: 03bd6aa1b0de
Create Date: 2023-05-23 16:27:33.130162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249185222e45'
down_revision = '03bd6aa1b0de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
